import * as fs from 'fs';
import * as path from 'path';
import { findProjectRoot, loadConfig } from './config';
import { getPrismaClientPath, hasCustomPrismaOutput } from './schema-parser';

/**
 * Generates the .prisma-flare directory with FlareClient configured for the project's
 * Prisma client output path.
 *
 * This function creates:
 * - node_modules/.prisma-flare/index.js (ESM)
 * - node_modules/.prisma-flare/index.cjs (CommonJS)
 * - node_modules/.prisma-flare/index.d.ts (TypeScript declarations)
 */
export function generateClient() {
  const rootDir = findProjectRoot(process.cwd());
  const config = loadConfig(rootDir);

  // Determine the Prisma client import path
  let prismaClientImport: string;

  if (config.prismaClientPath) {
    // User explicitly configured a path
    prismaClientImport = config.prismaClientPath;
  } else {
    // Auto-detect from schema.prisma
    prismaClientImport = getPrismaClientPath(rootDir);
  }

  // Resolve the import path for the generated file
  const nodeModulesDir = path.join(rootDir, 'node_modules');
  const prismaFlareDir = path.join(nodeModulesDir, '.prisma-flare');

  // Create the .prisma-flare directory
  if (!fs.existsSync(prismaFlareDir)) {
    fs.mkdirSync(prismaFlareDir, { recursive: true });
  }

  // Calculate the import path for the generated files
  let resolvedImport: string;

  if (prismaClientImport === '@prisma/client') {
    resolvedImport = '@prisma/client';
  } else {
    // Convert absolute path to relative path from .prisma-flare directory
    resolvedImport = path.relative(prismaFlareDir, prismaClientImport);
    if (!resolvedImport.startsWith('.')) {
      resolvedImport = './' + resolvedImport;
    }
    resolvedImport = resolvedImport.replace(/\\/g, '/');
  }

  const isCustomOutput = hasCustomPrismaOutput(rootDir);

  // Generate index.js (ESM)
  const esmContent = `// Generated by prisma-flare - DO NOT EDIT
// This file provides FlareClient configured for your Prisma client output path
// Import path: ${prismaClientImport}

import { PrismaClient, Prisma } from '${resolvedImport}';
import { createFlareClient } from 'prisma-flare';

// Create and export FlareClient using the factory
export const FlareClient = createFlareClient(PrismaClient, Prisma);

// Re-export PrismaClient and Prisma for convenience
export { PrismaClient, Prisma };
`;

  // Generate index.cjs (CommonJS)
  const cjsContent = `// Generated by prisma-flare - DO NOT EDIT
// This file provides FlareClient configured for your Prisma client output path
// Import path: ${prismaClientImport}

const { PrismaClient, Prisma } = require('${resolvedImport}');
const { createFlareClient } = require('prisma-flare');

// Create FlareClient using the factory
const FlareClient = createFlareClient(PrismaClient, Prisma);

module.exports = {
  FlareClient,
  PrismaClient,
  Prisma
};
`;

  // Generate index.d.ts (TypeScript declarations)
  const dtsContent = `// Generated by prisma-flare - DO NOT EDIT
// This file provides FlareClient configured for your Prisma client output path

import { PrismaClient as BasePrismaClient, Prisma as BasePrisma } from '${resolvedImport}';
import type { FlareClientOptions } from 'prisma-flare';
import type { ModelName } from 'prisma-flare';
import type FlareBuilder from 'prisma-flare/flareBuilder';

// Re-export PrismaClient and Prisma from the configured path
export { BasePrismaClient as PrismaClient, BasePrisma as Prisma };

// FlareClient type that extends the project's PrismaClient
export declare class FlareClient extends BasePrismaClient {
  constructor(options?: FlareClientOptions);

  /**
   * Creates a new FlareBuilder instance for the specified model.
   * @param modelName - The name of the model.
   * @returns FlareBuilder instance
   */
  from<T extends ModelName>(modelName: T): FlareBuilder<T>;

  /**
   * Executes a transaction with the FlareClient capabilities.
   * @param fn - The transaction function.
   * @param options - Transaction options.
   * @returns The result of the transaction.
   */
  transaction<R>(
    fn: (tx: FlareClient) => Promise<R>,
    options?: { maxWait?: number; timeout?: number; isolationLevel?: any }
  ): Promise<R>;
}
`;

  // Write the files
  fs.writeFileSync(path.join(prismaFlareDir, 'index.js'), esmContent);
  fs.writeFileSync(path.join(prismaFlareDir, 'index.cjs'), cjsContent);
  fs.writeFileSync(path.join(prismaFlareDir, 'index.d.ts'), dtsContent);

  // Create package.json for the generated module
  const packageJson = {
    name: '.prisma-flare',
    version: '0.0.0',
    main: './index.cjs',
    module: './index.js',
    types: './index.d.ts',
    type: 'module',
    exports: {
      '.': {
        types: './index.d.ts',
        import: './index.js',
        require: './index.cjs'
      }
    }
  };

  fs.writeFileSync(
    path.join(prismaFlareDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  );

  // Log success message
  if (isCustomOutput) {
    console.log(`✅ Generated prisma-flare client with custom Prisma output: ${prismaClientImport}`);
  } else {
    console.log(`✅ Generated prisma-flare client using @prisma/client`);
  }
  console.log(`   Location: ${prismaFlareDir}`);
  console.log(`\n   Import: import { FlareClient } from 'prisma-flare/client';`);
}
