import * as fs from 'fs';
import * as path from 'path';
import { loadConfig, findProjectRoot } from './config';

/**
 * Generates the callbacks index file (barrel) that imports all callback files.
 * This ensures callbacks work in all environments (bundlers, Node.js, etc.)
 */
export function generateCallbacksIndex(): void {
  const rootDir = findProjectRoot(process.cwd());
  const config = loadConfig(rootDir);
  const callbacksDir = path.join(rootDir, config.callbacksPath);

  if (!fs.existsSync(callbacksDir)) {
    console.log(`ℹ️  Callbacks directory not found: ${callbacksDir}`);
    return;
  }

  const files = fs.readdirSync(callbacksDir);
  const callbackFiles = files.filter(file => {
    // Include .ts and .js files, exclude index files and hidden files
    if (file === 'index.ts' || file === 'index.js' || file.startsWith('.')) {
      return false;
    }
    return file.endsWith('.ts') || file.endsWith('.js');
  });

  if (callbackFiles.length === 0) {
    console.log(`ℹ️  No callback files found in: ${callbacksDir}`);
    return;
  }

  // Generate imports without extensions (works for both TS and JS)
  const imports = callbackFiles
    .map(file => {
      const basename = file.replace(/\.(ts|js)$/, '');
      return `import './${basename}';`;
    })
    .join('\n');

  const content = `// AUTO-GENERATED by prisma-flare - DO NOT EDIT
// This file imports all callbacks to ensure they are registered.
// Re-run 'npx prisma-flare generate' after adding new callback files.

${imports}
`;

  const indexPath = path.join(callbacksDir, 'index.ts');
  fs.writeFileSync(indexPath, content);
  console.log(`✅ Generated callbacks index: ${callbacksDir}/index.ts (${callbackFiles.length} callbacks)`);
}
