/**
 * prisma-flare/client entry point
 *
 * This module provides FlareClient configured for your project's Prisma client output path.
 * It re-exports from node_modules/.prisma-flare/, which is generated by `prisma-flare generate`.
 *
 * IMPORTANT: Run `npx prisma-flare generate` before importing from this module.
 *
 * This module only exports FlareClient, Prisma, and PrismaClient.
 * For hooks, registries, and other utilities, import from 'prisma-flare' directly:
 *
 * @example
 * import { FlareClient } from 'prisma-flare/client';
 * import { hookRegistry, beforeCreate } from 'prisma-flare';
 */

// Re-export from generated .prisma-flare
// This is a static import - if .prisma-flare doesn't exist, you'll get a clear error
// telling you to run `npx prisma-flare generate`
export { FlareClient, Prisma, PrismaClient } from '.prisma-flare';
