/**
 * prisma-flare/client entry point
 *
 * This module provides FlareClient and FlareBuilder configured for your project's Prisma client.
 * It re-exports from node_modules/prisma-flare-generated/, which is generated by `prisma-flare generate`.
 *
 * IMPORTANT: Run `npx prisma-flare generate` before importing from this module.
 *
 * @example
 * import { FlareClient, FlareBuilder } from 'prisma-flare/client';
 *
 * // For hooks and utilities, import from 'prisma-flare' directly:
 * import { hookRegistry, beforeCreate } from 'prisma-flare';
 */

// Re-export from generated prisma-flare-generated
// This is a static import - if prisma-flare-generated doesn't exist, you'll get a clear error
// telling you to run `npx prisma-flare generate`
export { FlareClient, FlareBuilder, Prisma, PrismaClient } from 'prisma-flare-generated';
